"""initial_prd_v3_schema

Revision ID: 4fc7f70b0a5b
Revises: 
Create Date: 2026-09-14 20:12:40.237329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc7f70b0a5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_settings',
    sa.Column('system_setting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('system_setting_id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('audit_log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('previous_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('audit_log_id')
    )
    op.create_table('communication_records',
    sa.Column('communication_record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=100), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('communication_record_id')
    )
    op.create_table('customer_profiles',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('kyc_status', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('property_owner_profiles',
    sa.Column('owner_profile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('tin_number', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('kyc_status', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('owner_profile_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('security_events',
    sa.Column('security_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('security_event_id')
    )
    op.create_table('user_roles',
    sa.Column('user_role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_role_id')
    )
    op.create_table('authorization_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_profile_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_profile_id'], ['property_owner_profiles.owner_profile_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direct_asset_briefs',
    sa.Column('dab_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('budget_range', sa.String(length=150), nullable=True),
    sa.Column('brief_details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_profile_id'], ['property_owner_profiles.owner_profile_id'], ),
    sa.PrimaryKeyConstraint('dab_id')
    )
    op.create_table('global_service_agreements',
    sa.Column('agreement_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_profile_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('terms_reference', sa.String(length=255), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_profile_id'], ['property_owner_profiles.owner_profile_id'], ),
    sa.PrimaryKeyConstraint('agreement_id')
    )
    op.create_table('gold_accounts',
    sa.Column('gold_account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('current_points', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.customer_id'], ),
    sa.PrimaryKeyConstraint('gold_account_id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('gold_rewards',
    sa.Column('gold_reward_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.customer_id'], ),
    sa.PrimaryKeyConstraint('gold_reward_id')
    )
    op.create_table('kyc_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('government_id_data', sa.Text(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_profile_id'], ['property_owner_profiles.owner_profile_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('referral_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referrer_customer_id', sa.Integer(), nullable=False),
    sa.Column('referred_customer_id', sa.Integer(), nullable=False),
    sa.Column('referral_code_used', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('relationship_created_at', sa.DateTime(), nullable=False),
    sa.Column('qualified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referred_customer_id'], ['customer_profiles.customer_id'], ),
    sa.ForeignKeyConstraint(['referrer_customer_id'], ['customer_profiles.customer_id'], ),
    sa.PrimaryKeyConstraint('referral_id')
    )
    op.create_table('saved_searches',
    sa.Column('saved_search_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('search_criteria', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.customer_id'], ),
    sa.PrimaryKeyConstraint('saved_search_id')
    )
    op.create_table('transaction_codes',
    sa.Column('transaction_code_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_profile_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_profile_id'], ['property_owner_profiles.owner_profile_id'], ),
    sa.PrimaryKeyConstraint('transaction_code_id')
    )
    op.create_table('gold_events',
    sa.Column('gold_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gold_account_id', sa.Integer(), nullable=False),
    sa.Column('customer_profile_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points_change', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('new_balance', sa.Integer(), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.customer_id'], ),
    sa.ForeignKeyConstraint(['gold_account_id'], ['gold_accounts.gold_account_id'], ),
    sa.PrimaryKeyConstraint('gold_event_id')
    )
    op.create_table('properties',
    sa.Column('property_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dab_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('locality', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('bedroom_count', sa.Integer(), nullable=True),
    sa.Column('bathroom_count', sa.Integer(), nullable=True),
    sa.Column('land_area_sq_m', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('availability_status', sa.String(length=100), nullable=True),
    sa.Column('publication_status', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('available_from', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dab_id'], ['direct_asset_briefs.dab_id'], ),
    sa.PrimaryKeyConstraint('property_id'),
    sa.UniqueConstraint('dab_id')
    )
    op.create_table('referral_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.referral_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_cases',
    sa.Column('verification_case_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dab_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('verifier_type', sa.String(length=50), nullable=True),
    sa.Column('verification_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('result_details', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['dab_id'], ['direct_asset_briefs.dab_id'], ),
    sa.PrimaryKeyConstraint('verification_case_id')
    )
    op.create_table('applications',
    sa.Column('application_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.customer_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('inspections',
    sa.Column('inspection_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('inspector_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.customer_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ),
    sa.PrimaryKeyConstraint('inspection_id')
    )
    op.create_table('mandates',
    sa.Column('mandate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('mandate_type', sa.String(length=100), nullable=True),
    sa.Column('mandate_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.customer_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ),
    sa.PrimaryKeyConstraint('mandate_id')
    )
    op.create_table('offers',
    sa.Column('offer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('offer_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.customer_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_table('property_documents',
    sa.Column('document_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('owner_confirmation', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('property_media',
    sa.Column('media_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_table('saved_properties',
    sa.Column('saved_property_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.customer_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ),
    sa.PrimaryKeyConstraint('saved_property_id')
    )
    op.create_table('verification_events',
    sa.Column('verification_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('verification_case_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('performed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['verification_case_id'], ['verification_cases.verification_case_id'], ),
    sa.PrimaryKeyConstraint('verification_event_id')
    )
    op.create_table('letters_of_intent',
    sa.Column('letter_of_intent_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('offer_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ),
    sa.PrimaryKeyConstraint('letter_of_intent_id')
    )
    op.create_table('negotiations',
    sa.Column('negotiation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('counter_offer_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('proposed_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.offer_id'], ),
    sa.PrimaryKeyConstraint('negotiation_id')
    )
    op.create_table('performance_guarantees',
    sa.Column('guarantee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('owner_profile_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('mandate_id', sa.Integer(), nullable=True),
    sa.Column('guarantee_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('eligible_at', sa.DateTime(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('period_days', sa.Integer(), nullable=True),
    sa.Column('cycle_days', sa.Integer(), nullable=True),
    sa.Column('benefit_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cap_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('terms_version', sa.String(length=50), nullable=True),
    sa.Column('coverage_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.customer_id'], ),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.mandate_id'], ),
    sa.ForeignKeyConstraint(['owner_profile_id'], ['property_owner_profiles.owner_profile_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ),
    sa.PrimaryKeyConstraint('guarantee_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('transaction_type', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('transaction_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('odacity_commission_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('odacity_commission_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.customer_id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.offer_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('transaction_reference')
    )
    op.create_table('bank_guarantee_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('performance_guarantee_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performance_guarantee_id'], ['performance_guarantees.guarantee_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('performance_guarantee_id')
    )
    op.create_table('dispute_cases',
    sa.Column('dispute_case_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.customer_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('dispute_case_id')
    )
    op.create_table('guarantee_cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('performance_guarantee_id', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('cycle_start', sa.Date(), nullable=True),
    sa.Column('cycle_end', sa.Date(), nullable=True),
    sa.Column('days_elapsed', sa.Integer(), nullable=False),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performance_guarantee_id'], ['performance_guarantees.guarantee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guarantee_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('performance_guarantee_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performance_guarantee_id'], ['performance_guarantees.guarantee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guarantee_settlements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('performance_guarantee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('settlement_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performance_guarantee_id'], ['performance_guarantees.guarantee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('invoice_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('payment_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('invoice_id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('referral_rewards',
    sa.Column('referral_reward_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('qualifying_transaction_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('referrer_customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('transaction_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('odacity_earning', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reward_rate_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reward_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qualifying_transaction_id'], ['transactions.transaction_id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.referral_id'], ),
    sa.ForeignKeyConstraint(['referrer_customer_id'], ['customer_profiles.customer_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('referral_reward_id')
    )
    op.create_table('transaction_documents',
    sa.Column('transaction_document_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_document_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('transaction_ref', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('reconciliation_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('transaction_documents')
    op.drop_table('referral_rewards')
    op.drop_table('invoices')
    op.drop_table('guarantee_settlements')
    op.drop_table('guarantee_events')
    op.drop_table('guarantee_cycles')
    op.drop_table('dispute_cases')
    op.drop_table('bank_guarantee_references')
    op.drop_table('transactions')
    op.drop_table('performance_guarantees')
    op.drop_table('negotiations')
    op.drop_table('letters_of_intent')
    op.drop_table('verification_events')
    op.drop_table('saved_properties')
    op.drop_table('property_media')
    op.drop_table('property_documents')
    op.drop_table('offers')
    op.drop_table('mandates')
    op.drop_table('inspections')
    op.drop_table('applications')
    op.drop_table('verification_cases')
    op.drop_table('referral_events')
    op.drop_table('properties')
    op.drop_table('gold_events')
    op.drop_table('transaction_codes')
    op.drop_table('saved_searches')
    op.drop_table('referrals')
    op.drop_table('kyc_cases')
    op.drop_table('gold_rewards')
    op.drop_table('gold_accounts')
    op.drop_table('global_service_agreements')
    op.drop_table('direct_asset_briefs')
    op.drop_table('authorization_codes')
    op.drop_table('user_roles')
    op.drop_table('security_events')
    op.drop_table('property_owner_profiles')
    op.drop_table('notifications')
    op.drop_table('customer_profiles')
    op.drop_table('communication_records')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
